[package]
name = "pijul"
version = "0.1.0"
publish.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/pijul.rs"

[dependencies]
anyhow.workspace = true
gpui.workspace = true
workspace-hack.workspace = true
